name: "Evaluate pipeline"
description: "Get pipeline Evaluation from CVM"
author: "hoainamnv34"
inputs: 
 host:
    description: "Host of CVM"
    required: true
  project_id:
    description: "ID of Project In CVM"
    required: true
  pipeline_run_id:
    description: "pipeline_run_id"
    required: true
  latest_request:
    description: "latest_request"
    required: true
  # token:
  #   description: "Token for import"
  #   required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - --host 
  - "${{ inputs.host }}" 
  - --project_id 
  - "${{ inputs.project_id }}"
  - --pipeline_run_id
  - "${{ inputs.pipeline_run_id }}" 
  - --latest_request
  - "${{ inputs.latest_request }}"
