name: "Evaluate pipeline"
description: "Get pipeline Evaluation from CVM"
author: "hoainamnv34"
inputs: 
  host:
    description: "Host of CVM"
    required: true
  project_id:
    description: "ID of Project In CVM"
    required: true
  run_id:
    description: "run_id"
    required: true
  final_request:
    description: "final_request"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - --host 
  - "${{ inputs.host }}" 
  - --project_id 
  - "${{ inputs.project_id }}"
  - --run_id
  - "${{ inputs.run_id }}" 
  - --final_request
  - "${{ inputs.final_request }}"
